### ISSUE TITLE
'nlogo' issues

### ISSUE THREAD

**Issue by sirselim** [rayblick/sampling-game#4]
I noticed when I pulled in the recent version that the `nlogo` file was causing errors:

``` sh
Traceback (most recent call last):
  File "./sample_size.py", line 204, in <module>
    app = guessN(root)
  File "./sample_size.py", line 34, in __init__
    self.img = PhotoImage(file = "images//nlogo.gif").subsample(5, 5)
  File "/usr/lib/python3.4/tkinter/__init__.py", line 3419, in __init__
    Image.__init__(self, 'photo', name, cnf, master, **kw)
  File "/usr/lib/python3.4/tkinter/__init__.py", line 3375, in __init__
    self.tk.call(('image', 'create', imgtype, name,) + options)
_tkinter.TclError: couldn't open "images//nlogo.gif": no such file or directory
```

`nlogo` doesn't appear to have a file extension associated with it, but the script wants it to be a `.gif`. I tried renaming the file to `nlogo.gif`, but there are still errors:

``` sh
miles@lappy:~/gitrepos/testing/sampling-game$ ./sample_size.py 
Traceback (most recent call last):
  File "./sample_size.py", line 204, in <module>
    app = guessN(root)
  File "./sample_size.py", line 34, in __init__
    self.img = PhotoImage(file = "images//nlogo.gif").subsample(5, 5)
  File "/usr/lib/python3.4/tkinter/__init__.py", line 3419, in __init__
    Image.__init__(self, 'photo', name, cnf, master, **kw)
  File "/usr/lib/python3.4/tkinter/__init__.py", line 3375, in __init__
    self.tk.call(('image', 'create', imgtype, name,) + options)
_tkinter.TclError: couldn't recognize data in image file "images//nlogo.gif"
```

It seems that the file is only 1byte in size, maybe something went wrong with the upload?

After replacing the in script link to point at `logo.gif` (the llama) everything is working nicely. I like the addition of the histogram to the GUI application and can report that it all works perfectly.

  -- Miles

**Comment by rayblick** [comment]
Awesome! Thanks Miley! Unfortunately I didn't manage to upload the image
called nlogo.gif to Github. I think this is a sign that we have to stay
with our old friend the Llama !!!!
